### ISSUE TITLE
Setup / Update of sensor platform ecowater_softener is taking over 10 seconds

### ISSUE THREAD

**Issue by ZamliyMedre** [barleybobs/homeassistant-ecowater-softener#12]
Hi,

I have recently installed the ecowater-softener integration for Home Assistant 2022.2.9 via HACS.  Although integration seems to be working within Home Assistant, I do see the follow errors logged which comes up now and then.

Logger: homeassistant.components.sensor
Source: /usr/local/lib/python3.9/asyncio/events.py:80
Integration: Sensor (documentation, issues)
First occurred: 9:00:29 AM (1 occurrences)
Last logged: 9:00:29 AM

Setup of sensor platform ecowater_softener is taking over 10 seconds.

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:728
First occurred: 9:31:07 AM (1 occurrences)
Last logged: 9:31:07 AM

Update of sensor.ecowater_######### is taking over 10 seconds

![Capture3](https://user-images.githubusercontent.com/64253821/154928693-c1bb4469-f4ac-4545-acee-8efa68a5595c.JPG)

![Capture](https://user-images.githubusercontent.com/64253821/154929082-9ff01f1f-6548-44e0-95b1-fb935d2c54d0.JPG)

**Comment by figorr** [comment]
I can see the same error log after a fresh install

**Comment by barleybobs** [comment]
These are just warnings and can be ignored. This is just due to the EcoWater website being slow.

Thanks 👍
