### ISSUE TITLE
Only seeing one entity

### ISSUE THREAD

**Issue by reticulatingspline** [barleybobs/homeassistant-ecowater-softener#13]
Hi,

I recently installed v1.1.0 via Hacs. Did the setup with my DSN, u/p and I only see one "Entity" with the status and nothing else. I have no matching devices, however.

I didn't see anything on the documentation as to when the "one device with multiple attributes" screencap on your README would appear. 

https://i.imgur.com/8ymGBkc.png

**Comment by mblauser** [comment]
Click on that Ecowater entity that you now have.  It should bring up a window showing that it is Online.  Now click on the Attributes dropdown below the History and it will bring up a list of attributes of that entity.

https://imgur.com/a/HTrr3rx

**Comment by jcarlson04** [comment]
Good afternoon! 

I am having a problem with getting my entity to work. It keeps stating it is unavailable in the status. I can successfully log in to their website using the username/password. Any ideas? 

![image](https://user-images.githubusercontent.com/62529534/174137667-3b8cdbc1-9e3c-4a9f-aaf4-6fff723980ad.png)

**Comment by barleybobs** [comment]
Answered by @mblauser.

Thanks 👍

**Comment by puttemanp** [comment]
I have kind of the same problem since updating to the latest version. 
I had created a card where I had a view on all attributes/entities 
Since the updates all entities are unknown: https://imgur.com/a/bZXPiXK

However when I follow the procedure mentioned above all attributes are available.
Any insights?

**Comment by jcarlson04** [comment]
I am still getting unavailable, I have removed and added back multiple times.  Any ideas on why it is not connecting online? 
![image](https://user-images.githubusercontent.com/62529534/177081323-e34ba926-c40d-4b82-96f8-7041c812f778.png)
