### ISSUE TITLE
Status is unavailable

### ISSUE THREAD

**Issue by jcarlson04** [barleybobs/homeassistant-ecowater-softener#14]
Good afternoon!

I am having a problem with getting my entity to work. It keeps stating it is unavailable in the status. I can successfully log in to their website using the username/password. Any ideas?

![image](https://user-images.githubusercontent.com/62529534/174138321-c343579f-6f3b-4c7b-8070-0d29c47885af.png)

**Comment by jcarlson04** [comment]
The status is now online, but I can't access any settings. I only see what is shown below; what else am I missing? 

![image](https://user-images.githubusercontent.com/62529534/174647667-446b234a-c733-48d3-a626-90b1a2ae0796.png)

**Comment by barleybobs** [comment]
> The status is now online, but I can't access any settings. I only see what is shown below; what else am I missing?

All of the data is in the attributes of that sensor. Accessing these attributes is explained in #13. I hope this solves your issue.

If it does then if you could close it, that would be appreciated.

Thanks 👍

**Comment by barleybobs** [comment]
I saw your post in #13. Could you check the log please @jcarlson04.

Thanks :+1:

**Comment by jcarlson04** [comment]
Good morning, 

In the log I am getting the below messages. 

Error: local variable 'website_data' referenced before assignment
8:43:30 AM – (ERROR) Ecowater Softener (custom integration) - message first occurred at July 1, 2022 at 1:50:26 PM and shows up 183 times
Error connecting to "www.wifi.ecowater.com": HTTPSConnectionPool(host='www.wifi.ecowater.com', port=443): Max retries exceeded with url: /Site/Login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f71aa0880>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
8:43:30 AM – (ERROR) /usr/local/lib/python3.9/site-packages/ecowater_softener/ecowater.py - message first occurred at July 1, 2022 at 1:50:26 PM and shows up 183 times

**Comment by barleybobs** [comment]
Hey! 

This error is fixed with v2.0.0. Could you please install this update through HACS and see if you still get the error.

Thanks 👍
