### ISSUE TITLE
Add current GPM

### ISSUE THREAD

**Issue by magnetic157** [barleybobs/homeassistant-ecowater-softener#15]
Would it be possible to add the current GPM (water flow)?  

I believe it's possible going a back-route with AppDameon but it would be great if it could be incorporated into the native integration.  I had it working a while back with the below tutorial.

https://community.home-assistant.io/t/ecowater-softener-how-to-integrate-this-python-script/177263/11

**Comment by barleybobs** [comment]
It may be possible, but since the integration only updates every 30 minutes it would not be accurate.

**Comment by magnetic157** [comment]
That's odd, I thought it was more frequent then that.  When I had it setup prior with AppDameon I could have sworn it updated a lot more frequently then that.

**Comment by dtpazz** [comment]
I'd also be interested in this enhancement.  Could the integration call for data more regularly?

**Comment by almoney** [comment]
If we start a distributed attack on their servers they will shut us down like chamberlain MyQ...  maybe we can ask for an API for realtime data?

**Comment by laplac** [comment]
I'm interested in this feature as well. I can use this data to detect any water leaking when I'm out of home.

**Comment by almoney** [comment]
I think you can use total water once an hour to detect leaks as well.

**Comment by heisenberg2980** [comment]
It would be amazing to get real-time data about current water flow in the same way that you can see it in the ecowater app, and ideally using a local API so we don´t use ecowater servers and it´s a win-win (faster response for us, less server usage for ecowater), do we know if anyone has tried contacting ecowater and ask for this?

**Comment by barleybobs** [comment]
This has been added in [v4.0.0](https://github.com/barleybobs/homeassistant-ecowater-softener/releases/tag/v4.0.0) 🎉
