### ISSUE TITLE
Error connecting to "www.wifi.ecowater.com"

### ISSUE THREAD

**Issue by figorr** [barleybobs/homeassistant-ecowater-softener#16]
Hi, suddenly the integration stopped working and it it is showing the following two log errors:

`Logger: custom_components.ecowater_softener.sensor
Source: custom_components/ecowater_softener/sensor.py:111
Integration: Ecowater Softener (documentation, issues)
First occurred: 10:44:15 (1 occurrences)
Last logged: 10:44:15

Error: local variable 'website_data' referenced before assignment
Traceback (most recent call last):
  File "/config/custom_components/ecowater_softener/sensor.py", line 111, in async_update
    data_json = await self.hass.async_add_executor_job(lambda: ecowaterDevice._get())
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ecowater_softener/sensor.py", line 111, in <lambda>
    data_json = await self.hass.async_add_executor_job(lambda: ecowaterDevice._get())
  File "/usr/local/lib/python3.9/site-packages/ecowater_softener/ecowater.py", line 43, in _get
    tokens = request_validation_re.findall(website_data.text)
UnboundLocalError: local variable 'website_data' referenced before assignment` 

`Logger: root
Source: /usr/local/lib/python3.9/site-packages/ecowater_softener/ecowater.py:41
First occurred: 10:44:15 (1 occurrences)
Last logged: 10:44:15

Error connecting to "www.wifi.ecowater.com": HTTPSConnectionPool(host='www.wifi.ecowater.com', port=443): Max retries exceeded with url: /Site/Login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc5020b64f0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))`

The server seems to have changed the https address for the loggin...

The address [www.wifi.ecowater.com](https://www.wifi.ecowater.com) it is not available anymore.

The new available address is [wifi.ecowater.com](https://wifi.ecowater.com), so without www.

Is there any easy way to update the new loggin address or a new integration update will be necessary?

Thanks in advance.

**Comment by barleybobs** [comment]
Thanks for pointing this issue out. It should be fixed in [v2.0.0](https://github.com/barleybobs/homeassistant-ecowater-softener/releases/tag/v2.0.0). To fix all you should need to do is update the integration through HACS and potentially restart homeassistant.

Thanks 👍
