### ISSUE TITLE
Has ecowater changed their API

### ISSUE THREAD

**Issue by puttemanp** [barleybobs/homeassistant-ecowater-softener#17]
https://www.wifi.ecowater.com/Site/Login doesn't work anymore. The URL doesn't resolve.
https://wifi.ecowater.com/Site/Login resolves and works.

Result is that status of all sensors is unknown

**Comment by barleybobs** [comment]
This has been reported and resolved in issue #16. To fix it all you should need to do is update the integration to v2.0.0 through HACS and potentially restart homeassistant.

Thanks +1
