### ISSUE TITLE
installed but not showing up

### ISSUE THREAD

**Issue by Ardaganbao** [barleybobs/homeassistant-ecowater-softener#19]
Hello 

Maybe I am super dump but the integration  don't show up or I don't look on the right place.
I downloaded it via HACS 1.26.2
my HASS is 2022.7.5
the files are well in /config/custom_components/ecowater_softener (installed by hacs so no mistake I guess)
(HASS rebooted)
then I go to settings > devices & services> + add integration  and there is no ecowater
something wrong or  wrong way to install.
(it never asked for login and password, like writing in the doc)

**Comment by barleybobs** [comment]
Can you try uninstalling the integration through HACS, rebooting HA and then reinstalling the integration through HACS. If that doesn't work could you check/provide the log.

Thanks 👍

**Comment by barleybobs** [comment]
Great. Glad I could help!
