### ISSUE TITLE
Not updating every 30 minutes.

### ISSUE THREAD

**Issue by Elitaz** [barleybobs/homeassistant-ecowater-softener#21]
Hello, this integration not updating every 30 minutes.. Only update after ha restart.. automaticaly never..
In logs update of sensor.ecowater_* is taking over 10 seconds, but not updating..

**Comment by matebenyovszky** [comment]
Although it updates for me nicely, I also got these messages constantly:

> Logger: homeassistant.components.sensor
Source: runner.py:119
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 9:20:25 PM (38 occurrences)
Last logged: 11:03:37 PM
> 
> Setup of sensor platform rest is taking over 10 seconds.
> Setup of sensor platform ecowater_softener is taking over 10 seconds.

OR:

>Logger: homeassistant.helpers.entity
Source: helpers/entity.py:527
First occurred: 9:50:56 PM (3 occurrences)
Last logged: 10:59:17 PM
>
>Update of sensor.ecowater_ac000w007138272 is taking over 10 seconds

**Comment by barleybobs** [comment]
> Although it updates for me nicely, I also got these messages constantly:
> 
> > Logger: homeassistant.components.sensor
> > Source: runner.py:119
> > Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
> > First occurred: 9:20:25 PM (38 occurrences)
> > Last logged: 11:03:37 PM
> > Setup of sensor platform rest is taking over 10 seconds.
> > Setup of sensor platform ecowater_softener is taking over 10 seconds.
> 
> OR:
> 
> > Logger: homeassistant.helpers.entity
> > Source: helpers/entity.py:527
> > First occurred: 9:50:56 PM (3 occurrences)
> > Last logged: 10:59:17 PM
> > Update of sensor.ecowater_ac000w007138272 is taking over 10 seconds

These are just warnings and can be ignored. This is just due to the EcoWater website being slow.

**Comment by barleybobs** [comment]
> Hello, this integration not updating every 30 minutes.. Only update after ha restart.. automaticaly never.. In logs update of sensor.ecowater_* is taking over 10 seconds, but not updating..

@Elitaz are you still suffering from this issue? The update time in newer versions should be every 10 minutes.

**Comment by barleybobs** [comment]
I will close this issue due to a lack of activity. Feel free to re-open it if you need @Elitaz!
