### ISSUE TITLE
Question on format of how data is exported

### ISSUE THREAD

**Issue by rbcaixeta** [barleybobs/homeassistant-ecowater-softener#23]
Why not export one device and multiple entities for each attribute so that they can be used individually on dashboards and used on the new HA water usage tracking?

**Comment by ThePrincelle** [comment]
At the moment, it seems that the config flows only apply on 1 device, so you can add multiple devices just by setting another integration. I agree that it's not the cleanest but it works. 

I just created a PR that generates multiple entities: https://github.com/barleybobs/homeassistant-ecowater-softener/pull/27
Here's a sneak peak :
<img width="472" alt="entities" src="https://user-images.githubusercontent.com/52919205/208267798-90b5afcd-df2c-44d0-946a-8ff48757d8da.png">
