### ISSUE TITLE
Add sensor so it can be used in Energy Dashboard

### ISSUE THREAD

**Issue by misterymisery** [barleybobs/homeassistant-ecowater-softener#25]
It would be great if this integration could be used in Energy Dashboard where in new version Water is part of it. Is it doable?

**Comment by barleybobs** [comment]
This feature has now been added! There are now separate sensors in [v3.0.0](https://github.com/barleybobs/homeassistant-ecowater-softener/releases/tag/v3.0.0). Please make sure to follow the instructions to make sure you do not experience any issues.

Thanks :+1:
