### ISSUE TITLE
Enhancement - is it possible to add m3 usage sensor for energy dashboard? 

### ISSUE THREAD

**Issue by misterymisery** [barleybobs/homeassistant-ecowater-softener#30]
Enhancement - is it possible to add m3 usage sensor for energy dashboard? It would be great to see it in energy dashboard along with other used resources.

**Comment by barleybobs** [comment]
You should be able to add the `sensor.ecowater_serialnumber_water_used_today` sensor to the energy dashboard regardless of whether it is Liters or Gallons. Would you mind checking this?

Thanks :+1:

**Comment by misterymisery** [comment]
> You should be able to add the `sensor.ecowater_serialnumber_water_used_today` sensor to the energy dashboard regardless of whether it is Liters or Gallons. Would you mind checking this?
> 
> Thanks 👍

It worked! Tahnk you very much! What a great integration!

**Comment by barleybobs** [comment]
No problem! I'll close this issue now.

Thanks :+1:
