### ISSUE TITLE
Add water use per day

### ISSUE THREAD

**Issue by zuzuman** [barleybobs/homeassistant-ecowater-softener#4]
# Query the JSON endpoint for the additional data
        
        additionalData = s.get('https://www.wifi.ecowater.com/Dashboard/GraphBy?by=week&date=' + str(today.strftime("%Y-%m-%d")) + '&dsn=' + str(dsn['dsn']), headers=headers)
        self._attrs[ATTR_WATER_USE_PER_DAY] = data_json[json.loads(additionalData.text)]

Thanks :)

**Comment by barleybobs** [comment]
Sorry for the long wait for this feature. There are now separate sensors in [v3.0.0](https://github.com/barleybobs/homeassistant-ecowater-softener/releases/tag/v3.0.0). Please make sure to follow the instructions to make sure you do not experience any issues.

Thanks :+1:
