### ISSUE TITLE
No entities found

### ISSUE THREAD

**Issue by cedricdelecole** [barleybobs/homeassistant-ecowater-softener#40]
Hi there,

I have an Ecowater "eVOLUTION REFINER POWER" model, the integration has bin done, but I see no entities which I can use.
I only see 1 entry, but no entities 👍 
<img width="275" alt="image" src="https://github.com/barleybobs/homeassistant-ecowater-softener/assets/135960043/3ccc9cee-3586-49f6-a8dc-f8f9d7d31457">

Something I am missing in here ?

Many thanks for the work !

**Comment by bradb1** [comment]
Same issue, has anyone solved?

**Comment by barleybobs** [comment]
@cedricdelecole are you still suffering from this issue?

**Comment by barleybobs** [comment]
I will close this issue due to a lack of activity. Feel free to re-open it if you need @cedricdelecole!
