### ISSUE TITLE
French Integration

### ISSUE THREAD

**Issue by dkp-consult** [barleybobs/homeassistant-ecowater-softener#57]
Hello,

I like your HACS Ecowater Integration, initially I want to dev myself, but your integration works great. 

In the 'Contributor' section, I see a thanks for french translation, but I don't see how french translation was. Can you tell me more ? 

If I've the time, can I create a drop menu for language of integration and create a pull request ? 

Thanks,
dkp

**Comment by barleybobs** [comment]
Thanks for your interest but as you have noticed there are already french translations that can be found here, https://github.com/barleybobs/homeassistant-ecowater-softener/blob/main/custom_components/ecowater_softener/translations/fr.json.

**Comment by dkp-consult** [comment]
Yeah I see that, but I would like to have a French or another language, view in HA dashboard. 

ie translate 'out of salt on' in french.

**Comment by barleybobs** [comment]
I'm not sure if there is an easy way to implement that in the integration. You can always rename sensors within Homeassistant.

**Comment by dkp-consult** [comment]
I'll try and give you a feedback. 

My thinking method is add a translation option after the installation.

**Comment by barleybobs** [comment]
That could potentially work. I have never seen it implemented in another integration like that. I wonder if there is a way to use the strings json, because those are auto-detected based on location.

**Comment by barleybobs** [comment]
I am going to close this issue for now if you have any further ideas please do reopen it or open a pull request!
