### ISSUE TITLE
Can't update to 3.3.0 ?

### ISSUE THREAD

**Issue by cedricdelecole** [barleybobs/homeassistant-ecowater-softener#58]
Hello, I currently have release 3.0.0, but it seems like a version 3.3.0 is available ?
How can we install the latest version ?

Many Thanks !

**Comment by barleybobs** [comment]
Sorry for the late response. If you are using HACS then instructions can be found at https://www.hacs.xyz/docs/use/update/#updating-hacs

**Comment by barleybobs** [comment]
I will close this issue due to a lack of activity. Feel free to re-open it if you need @cedricdelecole!
