### ISSUE TITLE
Feature Request: Water Flow Sensor

### ISSUE THREAD

**Issue by CowboyGravy** [barleybobs/homeassistant-ecowater-softener#69]
Would it be possible to include the water flow value? 
[PyPi Page](https://pypi.org/project/ecowater-softener/#:~:text=%23%20returns%20%27the%20amount%20of%20water%20flow%27%20as%20an%20integer%0AecowaterDevice.waterFlow())

**Comment by barleybobs** [comment]
This has been added in [v4.0.0](https://github.com/barleybobs/homeassistant-ecowater-softener/releases/tag/v4.0.0) 🎉
