### ISSUE TITLE
No possibility to change units in 4.0.0

### ISSUE THREAD

**Issue by R1DEN** [barleybobs/homeassistant-ecowater-softener#72]
Hi, I've updated to 4.0.0 to solve the no data issue, but now I only have gallons in the entities. Is it possible to pick metric?

**Comment by barleybobs** [comment]
It is shown in the README [here](https://github.com/barleybobs/homeassistant-ecowater-softener?tab=readme-ov-file#changing-units).

**Comment by R1DEN** [comment]
Oops, sorry for that. Didn't scroll the readme enough. Thanks! 🙏
