### ISSUE TITLE
Does a list of supported devices excist?

### ISSUE THREAD

**Issue by Hoekeren** [barleybobs/homeassistant-ecowater-softener#73]
Hi 
I am in the marked for at watersoftner and stumbled over your project. 
Eowater is producing several models for different markeds some under the brand of ecowater others under other brands. 
Is there a list of supportet products or brands? 
I am not shure if all connected models use the same api disregarding the fact that they use different apps. 
Thanx for you effort to support the HA project :-)
Kind regards 
Christian (Hoekeren)

**Comment by barleybobs** [comment]
I have one of the evolution eVOLUTION BOOST water softeners, which it works with. I believe it should work with any of the salt-based Ecowater softeners.

**Comment by Hoekeren** [comment]
Interesting, I might have the opportunity to test it with two other different brands. I will let you know if I get the opportunity.Med venlig hilsenChristianFra: barleybobs ***@***.***>Sendt: tirsdag, oktober 1, 2024 4:54:31 PMTil: barleybobs/homeassistant-ecowater-softener ***@***.***>Cc: Hoekeren ***@***.***>; Author ***@***.***>Emne: Re: [barleybobs/homeassistant-ecowater-softener] Does a list of supported devices excist? (Issue #73)
I have one of the evolution eVOLUTION BOOST water softeners, which it works with. I believe it should work with any of the salt-based Ecowater softeners.

**Comment by barleybobs** [comment]
That would be great! Please do report back with any findings 👍 

Should I close this issue for now?

**Comment by Hoekeren** [comment]
You can close it and I will get back to you 👍Med venlig hilsenChristianFra: barleybobs ***@***.***>Sendt: tirsdag, oktober 1, 2024 6:34:12 PMTil: barleybobs/homeassistant-ecowater-softener ***@***.***>Cc: Hoekeren ***@***.***>; Author ***@***.***>Emne: Re: [barleybobs/homeassistant-ecowater-softener] Does a list of supported devices excist? (Issue #73)
That would be great! Please do report back with any findings 👍
Should I close this issue for now?

**Comment by barleybobs** [comment]
Awesome thanks 👍

**Comment by Hoekeren** [comment]
Hi. 
The Danish distributør of the Leycosoft brand from ecowater, have been in contact with ecowater who have stated the this brand will not work with your integration. Sadly they have not elaborated upon why and if the could provide any information on how to make it possible😭
