### ISSUE TITLE
Wrong Percentage Salt Level and missing status sensor

### ISSUE THREAD

**Issue by figorr** [barleybobs/homeassistant-ecowater-softener#75]
Thank you @barleybobs for this great update. The integration looks wonderful.

Just a couple of things.

1. Wrong "Salt Level Percentage" value.

   I have just noticed that the salt level percentage is showing a wrong value.

   I can see "Salt level Percentage" at 80% but the app and the device (physically) it is showing 50%, which is the right value.

   My alert level alert is set to 20 days ... Is it possible that "Salt Level Percentage" is using this value to some calculation instead using the proper attribute?

2. Status sensor is missing.

   Is it possible to recover this sensor? It was very useful to prepare an automation that sends a notification when the device is "Offline" (due to a powerloss or internet problem)

**Comment by barleybobs** [comment]
> Thank you @barleybobs for this great update. The integration looks wonderful.
> 
> Just a couple of things.
> 
> 1. Wrong "Salt Level Percentage" value.
>    I have just noticed that the salt level percentage is showing a wrong value.
>    I can see "Salt level Percentage" at 80% but the app and the device (physically) it is showing 50%, which is the right value.
>    My alert level alert is set to 20 days ... Is it possible that "Salt Level Percentage" is using this value to some calculation instead using the proper attribute?
> 2. Status sensor is missing.
>    Is it possible to recover this sensor? It was very useful to prepare an automation that sends a notification when the device is "Offline" (due to a powerloss or internet problem)

1. The new API only provides salt level in "tenths". When programming my salt level was at 60% and the API was reporting 30 so I presumed it was a simple x2 scale. But for you the API appears to be reporting 40 tenths which should be 50%. Not currently sure how the conversion should work? Not sure if anyone else would have an idea?
2. Potentially, but I'm not sure if it really fits in with how other integrations handle devices going offline. I would prefer that sensors became unavailable.

**Comment by Marianp90** [comment]
Agree that there is a bug. My sensor currently shows 140 % - app shows 87.5 %.

**Comment by barleybobs** [comment]
Ok so from that I can tell when salt level tenths is

30 -> 60%
40 -> 50%
70 -> 87.5%

Now I am even more confused 😕

**Comment by barleybobs** [comment]
**Update**

Looking at it I think it varies from model to model as all of them have different max salt levels

**Comment by barleybobs** [comment]
Yeah, there are device configs that the app uses to make the conversion, not sure how to get them. 

@Marianp90 Would you mind sharing the model of your water softener? Thanks 👍

**Comment by Marianp90** [comment]
Sure, mine is eVOLUTION 600 Power

**Comment by barleybobs** [comment]
@figorr @Marianp90 This should be fixed in [v4.1.0](https://github.com/barleybobs/homeassistant-ecowater-softener/releases/tag/v4.1.0) if you wouldn't mind updating and letting me know if it is fixed!

**Comment by figorr** [comment]
It's fixed in v.4.1.0.  At least for me. It is showing 50%, as it should be according to the app.

**Comment by Marianp90** [comment]
Indeed, for me the issue has been fixed as well. Showing 87.5 % - thank you!

**Comment by barleybobs** [comment]
That's great. Should I close this issue and you can open one regarding the status sensor?

**Comment by figorr** [comment]
Fixed in v4.1.0.
